# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestSpira' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'GoogleSignIn', '~> 6.2.4'
  pod 'Toast-Swift', '~> 5.0.1'
  pod 'SDWebImage', '~> 5.13.2'
  pod 'SkeletonView', '~> 1.30.4'
  # Pods for TestSpira

end
